project:
  type: website

website:
  title: "Liz Wagner"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - DataAnalysisProj1_final.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual
execute: 
  freeze: auto

